name: Run unit tests

on:
  workflow_dispatch:
  push:
    branches: '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: npm
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm test
    - name: Run type checks
      run: npm run typecheck
